services:
  cerebrumdb:
    build: .
    container_name: cerebrumdb
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - TRANSFORMER_MODEL=all-mpnet-base-v2
      - CONTINUAL_LEARNING=true
      - DATA_STORE_TYPE=json
      - VECTOR_INDEX_PATH=vector_index/index.faiss
      - REDIS_HOST=redis 
      - REDIS_PORT=6379
    restart: unless-stopped
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6380:6379"
    restart: unless-stopped
